In [1]:
%load_ext autoreload
%autoreload 2

In [13]:
from mebe.data import SequencesDataModule, SequencesDataset
import numpy as np

In [7]:
data = SequencesDataset.TEST

In [88]:
seqs = np.array(
    [s['keypoints'].reshape(-1, 11, 24 * 2) for s in data['sequences'].values()]
)
seq = seqs[0]
seq.shape

(4500, 11, 48)

In [89]:
np.sum(np.isnan(seqs[1])) // 48

4500

In [92]:
np.any(np.sum(seq_nan, axis=1), axis=1)

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [93]:
seqs.shape

(543, 4500, 11, 48)

In [95]:
seqs_t = seqs.transpose(0, 2, 1, 3)
seqs_t.shape

(543, 11, 4500, 48)

In [96]:
seqs_nan = np.isnan(seqs_t)

In [97]:
seq_nan_sum = np.sum(seqs_nan, axis=(-1, -2))

In [108]:
np.sum(seq_nan_sum == 4500 * 48)

634

In [105]:
np.prod(seq_nan_sum.shape)

5973

In [115]:
685 - 634

51

In [116]:
 (685 - 634) / 634

0.0804416403785489

In [109]:
634 / 5973

0.10614431608906746

In [106]:
685 / 5973

0.11468273899213126

In [118]:
# Verdict: it is ok to remove non-whole missing flies - they are a small amount

In [117]:
whole_misses = []

for i, seq in enumerate(seqs):
    seq_nan = np.isnan(seq)
    seq_nan = seq_nan.transpose(1, 0, 2)
    whole_flie_misses = np.sum(seq_nan, axis=(1, 2))
#     print(whole_flie_misses // 48)

In [1]:
import torch

In [2]:
t = torch.arange(10)

In [4]:
t.unfold(dimension=0, size=2, step=1)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7],
        [7, 8],
        [8, 9]])

In [5]:
from mebe.model import PositionalEncoding

In [30]:
inp = torch.arange(40).view(1, 2, 20)
inp

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
          17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
          37, 38, 39]]])

In [36]:
pos_enc = PositionalEncoding(d_model=2)

In [37]:
pos_enc.pe.shape

torch.Size([5000, 1, 2])

In [32]:
pos_enc.pe.shape

torch.Size([5000, 1, 20])

In [34]:
pos_enc(inp).shape

torch.Size([1, 2, 20])